# syntax=docker/dockerfile:1

FROM node:18

WORKDIR /app

COPY ["package.json", "package-lock.json", "./"]

RUN npm install
RUN npm install -g prisma

COPY . .

RUN prisma generate




CMD ["sh" , "./server.sh"]