version: '3.9'
services:
  server:
    build: 
      dockerfile: Dockerfile.dev
    platform: linux/arm64
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://root:example@database:3306/se100
      - JWT.SECRET = 'sercet'
      - JWT.EXPIRESIN = '1h'
      - BCRYPT_SALT_ROUND=10
      - CLIENT_DOMAIN=http://localhost
    networks:
      - app-network
    ports:
      - 80:3000
    volumes:
      - ./src:/app/src
    depends_on:
      - database
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: se100
    ports:
      - 3306:3306
    networks:
      - app-network
    volumes:
      - se100-mysql-db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    networks:
      - app-network
    ports:
      - 8080:8080
    depends_on:
      - database
volumes:
  se100-mysql-db:
networks:
  app-network: {}