# syntax=docker/dockerfile:1

FROM node:16

WORKDIR /app

COPY ["package.json", "package-lock.json", "./"]

RUN npm install
RUN npm install -g prisma

COPY . .

RUN prisma generate



CMD ["npm", "run", "start:dev"]