version: '3.9'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
     - app-network
    depends_on:
      - server
    command: [nginx-debug, '-g', 'daemon off;']
  server:
    build: 
      dockerfile: Dockerfile.server.dev
    platform: linux/arm64
    env_file:
      - .env.dev
    networks:
      - app-network
    volumes:
      - ./src:/app/src
      - ./src/infrastructure/services/send-email.service/reset-email.template.ejs:/app/dist/infrastructure/services/send-email.service/reset-email.template.ejs
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: se100
    ports:
      - 3306:3306
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password
    # volumes:
    #   - se100-mysql-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
  adminer:
    image: adminer
    restart: always
    networks:
      - app-network
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
  migration:
    build: 
      dockerfile: Dockerfile.prisma.dev
    platform: linux/arm64
    env_file:
      - .env.dev
    networks:
      - app-network
    volumes:
      - ./prisma:/app/prisma:ro
    depends_on:
      db:
        condition: service_healthy
networks:
  app-network: